import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    coverage: {
      enabled: true,
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.test.tsx",
        "src/test/**",
        // A thin Web Worker wrapper with no branching logic; covered by the browser tests.
        "src/infrastructure/engine/engine-transport.ts",
      ],
      include: [
        "src/app/**/*.ts",
        "src/app/**/*.tsx",
        "src/application/bootstrap/**/*.ts",
        "src/application/game-creation/**/*.ts",
        "src/application/game-session/**/*.ts",
        "src/application/history/**/*.ts",
        "src/application/opponent/**/*.ts",
        "src/application/preferences/**/*.ts",
        "src/application/persistence/**/*.ts",
        "src/application/recovery/**/*.ts",
        "src/features/**/*.ts",
        "src/features/**/*.tsx",
        "src/infrastructure/composition/**/*.ts",
        "src/infrastructure/engine/**/*.ts",
        "src/infrastructure/identity/**/*.ts",
        "src/infrastructure/opponent/**/*.ts",
        "src/infrastructure/time/**/*.ts",
        "src/infrastructure/config/persistence-config.ts",
        "src/infrastructure/persistence/**/*.ts",
      ],
      provider: "v8",
      reporter: ["text", "json-summary"],
      thresholds: {
        "src/application/{bootstrap,game-session,history,recovery}/**/*.ts": {
          branches: 85,
          functions: 90,
          lines: 88,
          statements: 88,
        },
        "src/application/game-creation/**/*.ts": {
          branches: 85,
          functions: 90,
          lines: 88,
          statements: 88,
        },
        "src/application/opponent/**/*.ts": {
          branches: 85,
          functions: 90,
          lines: 88,
          statements: 88,
        },
        "src/app/**/*.{ts,tsx}": {
          branches: 80,
          functions: 85,
          lines: 85,
          statements: 85,
        },
        "src/features/game-setup/**/*.tsx": {
          branches: 85,
          functions: 85,
          lines: 85,
          statements: 85,
        },
        "src/features/recovery/**/*.tsx": {
          branches: 85,
          functions: 85,
          lines: 85,
          statements: 85,
        },
        "src/features/game-shell/**/*.{ts,tsx}": {
          branches: 80,
          functions: 85,
          lines: 85,
          statements: 85,
        },
        "src/infrastructure/composition/**/*.ts": {
          branches: 85,
          functions: 90,
          lines: 90,
          statements: 90,
        },
        branches: 80,
        functions: 85,
        lines: 85,
        statements: 85,
      },
    },
    environment: "jsdom",
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    maxWorkers: 4,
    setupFiles: ["src/test/setup.ts"],
  },
});
