/** Public package version for diagnostics during the foundation phase. */
export const CHESS_CORE_VERSION = "0.1.0" as const;

export { ChessJsRulesAdapter } from "./adapters/chess-js-rules-adapter";
export {
  commitClockMove,
  createClock,
  pauseClock,
  projectClockDisplay,
  rebaseActiveClock,
  resumeClock,
  snapshotClock,
  startClock,
  stopClock,
  type ClockDisplay,
  type ClockDisplayProjectionResult,
  type ClockMoveCommitResult,
  type ClockRebaseResult,
  type ClockRemaining,
  type ClockSnapshotResult,
  type ClockState,
  type ClockTransitionRejectionReason,
  type ClockTransitionResult,
  type TimeControl,
  type TimedClockState,
  type TimedTimeControl,
} from "./domain/clock";
export {
  parseClockDurationMs,
  parseClockIncrementMs,
  parseMonotonicTimestampMs,
  type ClockDurationMs,
  type ClockIncrementMs,
  type MonotonicTimestampMs,
} from "./domain/clock-primitives";
export {
  createGameLifecycleState,
  transitionGameLifecycle,
  type GameLifecycleEvent,
  type GameLifecycleFailure,
  type GameLifecycleFailureCode,
  type GameLifecycleState,
  type GameLifecycleTransitionRejectionReason,
  type GameLifecycleTransitionResult,
  type GamePhase,
  type ResumableGamePhase,
} from "./domain/game-lifecycle";
export {
  createGameController,
  type CreateGameControllerOptions,
  type GameCommandRejectedResult,
  type GameCommandRejectionReason,
  type GameCommandResult,
  type GameController,
  type GameMoveCommandResult,
  type OpponentRequestCommandResult,
} from "./domain/game-controller";
export {
  GAME_SESSION_CHECKPOINT_VERSION,
  type GameSessionCheckpoint,
  type GameSessionCheckpointVersion,
} from "./domain/game-checkpoint";
export { type GameDomainEvent } from "./domain/game-events";
export {
  type RestartGameCommandResult,
  type RestartGameRejectionReason,
  type UndoMoveCommandResult,
  type UndoMoveRejectionReason,
} from "./domain/game-recovery";
export {
  restoreGameController,
  type GameControllerRestorationResult,
  type GameRestorationRejectionReason,
  type RestoreGameControllerOptions,
} from "./domain/game-restoration";
export {
  createAbandonedGameResult,
  createTimeoutGameResult,
  type AbandonedGameResult,
  type CompletedGameResult,
  type DecisiveGameResult,
  type DecisiveGameResultReason,
  type DrawGameResult,
  type DrawGameResultReason,
  type GameResult,
  type PgnResultToken,
} from "./domain/game-result";
export {
  createGameConfiguration,
  type AbandonGameCommand,
  type GameConfiguration,
  type GameParticipant,
  type GameParticipants,
  type GameSession,
  type HumanMoveCommand,
  type InitialPosition,
  type MoveRecord,
  type OpponentMoveProposal,
  type OpponentRequestFailureCommand,
  type OpponentRequestFailureReason,
  type OpponentRequestState,
  type ParticipantKind,
  type PositionSnapshot,
  type RequestOpponentMoveCommand,
  type RestartGameCommand,
  type UndoMoveCommand,
} from "./domain/game-session";
export {
  moveInputFromUci,
  type AppliedMove,
  type ChessMove,
  type ChessPosition,
  type ChessRulesPort,
  type DrawReason,
  type LegalMove,
  type LegalMoveQuery,
  type MoveApplicationResult,
  type MoveInput,
  type MoveRejectionReason,
  type PieceType,
  type PromotionPiece,
  type TerminalState,
  type UndoResult,
} from "./domain/chess-rules";
export {
  ChessRulesAdapterError,
  DomainValidationError,
  GameControllerError,
  type DomainValidationErrorCode,
  type GameControllerErrorCode,
} from "./domain/errors";
export {
  parseFen,
  parseColor,
  parseGameId,
  parsePgn,
  parsePly,
  parseRequestId,
  parseSanMove,
  parseSessionRevision,
  parseSquare,
  parseUciMove,
  parseUndoPlyCount,
  type Color,
  type Fen,
  type GameId,
  type Pgn,
  type Ply,
  type RequestId,
  type SanMove,
  type SessionRevision,
  type Square,
  type UciMove,
  type UndoPlyCount,
} from "./domain/primitives";
